# 一致性构建镜像 buildah bud --no-cache -f Dockerfile -t docker.io/aspnmy/debian-ssh:python3-mini
# support@e2bank.cn
# 重新规划构建更小的中间镜像
FROM aspnmy/telegram_mihao_bot_docker:v0.2


RUN cd  /app/Telegram-interactive-bot && git pull

WORKDIR /app/Telegram-interactive-bot
# 暴露50002端口 钱包端口
#EXPOSE 50002
EXPOSE 622


# 设置s6-overla:v${S6_OVERLAY_VERSION}全局的ENTRYPOINT
ENTRYPOINT ["/init"]
# Electrum  钱包默认开机不启动
CMD [ "botrun.sh" ]