# 一致性构建镜像 buildah bud --no-cache -f Dockerfile -t docker.io/aspnmy/debian-ssh:python3-mini
# support@e2bank.cn
# 重新规划构建更小的中间镜像
FROM aspnmy/debian-ssh:latest

#### --构建主服务${S6_OVERLAY_SERVIES}语句-开始
# 更新软件包列表 设置初始root密码
RUN apt-get update && apt-get install -y python3 python3-pip wget  && echo 'root:root@#1314' | chpasswd
# 清理缓存减小容器体积
RUN  apt-get autoclean && apt-get clean && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/* && rm -rf /tmp_srv/*



#### --构建主服务${S6_OVERLAY_SERVIES}语句-结束

# 暴露50002端口 钱包端口
#EXPOSE 50002
EXPOSE 622


# 设置s6-overla:v${S6_OVERLAY_VERSION}全局的ENTRYPOINT
ENTRYPOINT ["/init"]
# Electrum  钱包默认开机不启动
CMD [ "/usr/sbin/sshd" ]